version: '3.9'

services:
  api:
    container_name: smart_parking_user_svc
    image: smart_parking_user_svc:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    env_file: .env
    ports:
      - '5001:5001'
      - '50051:50051'
    expose:
      - '5001'
      - '50051'
    networks:
      - kong-net
    volumes:
      - .:/api
    # restart: unless-stopped
    tty: true
    stdin_open: true
  database:
    container_name: smart_parking_user_postgres
    image: postgres:12
    env_file: .env
    environment:
      - POSTGRES_USER=smart_parking_user
      - POSTGRES_DB=smart_parking_user
      - POSTGRES_PASSWORD=secret
    volumes:
      - user-postgres-data:/var/lib/postgresql/data
    networks:
      - kong-net
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  kong-net:
    external: true

volumes:
  user-postgres-data:
